name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast-tools:
    name: Semgrep + Gitleaks + PHPStan
    runs-on: ubuntu-latest
    container:
      image: nosferatuvjr/devsecops-tools:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep --config=auto --json > semgrep-output.json

      - name: Run Gitleaks
        run: git config --global --add safe.directory . && gitleaks detect --source=. --report-format=json --report-path=gitleaks-output.json

      - name: Run PHPStan
        run: phpstan analyse --no-progress --error-format=json > phpstan-output.json || true

      - name: Upload results to DefectDojo
        if: env.DEFECTDOJO_API_KEY != ''
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          ENGAGEMENT_ID: 5
        run: |
          function upload() {
            scan_type=$1
            file=$2
            curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -H "Content-Type: multipart/form-data" \
              -F "scan_type=$scan_type" \
              -F "engagement=$ENGAGEMENT_ID" \
              -F "file=@$file" \
              -F "verified=true" \
              -F "active=true" \
              -F "minimum_severity=Low" \
              -F "close_old_findings=true"
          }

          upload "Semgrep JSON Report" semgrep-output.json
          upload "Gitleaks" gitleaks-output.json
          upload "PHPStan" phpstan-output.json
